version: "3.9"
services:
  api:
    build: .
    image: secdataextractor-api:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./downloads:/app/downloads
      - ./output:/app/output
      - ./temp:/app/temp
    restart: unless-stopped
